export const plans = [
    {
        id: 'free',
        name: 'Free',
        price: '$0',
        period: '/ month',
        desc: 'Everything you need to get started — free forever.',
        max_locator: 1,
        max_location: 20,
        max_sub_domain: 1,
        features: [
            { ok: true, text: '1 Free locator' },
            { ok: true, text: 'Up to 20 locations' },
            { ok: true, text: 'Basic customization' },
            { ok: true, text: 'CSV import' },
            { ok: true, text: 'Embed on any website' },
            { ok: true, text: '1 Custom sub domains' },
            { ok: false, text: 'Basic analytics' },
            { ok: false, text: 'Analytics & insights & heatmap' },
            { ok: false, text: 'API access' },
            { ok: false, text: 'Remove Storefindy branding' },
        ],
        cta: 'Get started free',
        ctaClass: 'free',
    },
    {
        id: 'pro',
        name: 'Pro',
        price: '$10',
        period: '/ month',
        desc: 'For growing businesses that need more power and no branding.',
        badge: 'Most popular',
        featured: true,
        max_locator: 3,
        max_location: 500,
        max_sub_domain: 3,
        features: [
            { ok: true, text: '3 locators' },
            { ok: true, text: 'Up to 500 locations' },
            { ok: true, text: 'Semi customization' },
            { ok: true, text: 'CSV import' },
            { ok: true, text: 'Embed on any website' },
            { ok: true, text: '3 Custom sub domains' },
            { ok: true, text: 'Basic analytics' },
            { ok: false, text: 'Advanced insights & heatmap' },
            { ok: false, text: 'API access' },
            { ok: false, text: 'Remove Storefindy branding' },
        ],
        cta: 'Start Pro free trial',
        ctaClass: 'pro',
    },
    {
        id: 'business',
        name: 'Business',
        price: '$30',
        period: '/ month',
        desc: 'For multi-location brands that need full insights and scale.',
        max_locator: 10,
        max_location: 0,
        max_sub_domain: 7,
        features: [
            { ok: true, text: '10 locators' },
            { ok: true, text: 'Unlimited locations' },
            { ok: true, text: 'Full customization' },
            { ok: true, text: 'CSV import' },
            { ok: true, text: 'Embed on any website' },
            { ok: true, text: '7 Custom sub domains' },
            { ok: true, text: 'Advanced analytics & heatmap' },
            { ok: true, text: 'API access' },
            { ok: true, text: 'Remove Storefindy branding' },
            { ok: true, text: 'Priority support' },
        ],
        cta: 'Contact sales',
        ctaClass: 'biz',
    },
];