import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../../styles/globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import StoreProvider from '@/providers/StoreProvider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	robots: {
		index: false,
		follow: false,
	},
};

type Props = {
	children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className="min-h-full flex flex-col">
				<StoreProvider>
					<NextIntlClientProvider locale={locale} messages={messages}>
						<Header />
						<main className="main">
							{children}
						</main>
						<Footer />
					</NextIntlClientProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
